### ISSUE TITLE
Parser for ADD command is not bool_ok

### ISSUE THREAD

**Issue by rudmac** [RedisTimeSeries/redistimeseries-py#12]
When use the command on python:

```
127.0.0.1:6379> TS.ADD rates:ABEV3 1528837200 18.21
(integer) 1528837200
```

Will return an interger, not OK.

**client.py**
```
...
def __init__(self, *args, **kwargs):
        Redis.__init__(self, *args, **kwargs)
           
        # Set the module commands' callbacks
        MODULE_CALLBACKS = {
            self.CREATE_CMD : bool_ok,
            self.ADD_CMD : bool_ok,
            self.INCRBY_CMD : bool_ok,
            self.DECRBY_CMD : bool_ok,
            self.CREATERULE_CMD : bool_ok,
            self.DELETERULE_CMD : bool_ok,
            self.RANGE_CMD : parse_range,
            self.MRANGE_CMD : parse_m_range,
            self.GET_CMD : lambda x: (int(x[0]), float(x[1])),
            self.INFO_CMD : parse_info,
        }
...
```

`Redis server v=5.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=4d0898999c5f857`

```
127.0.0.1:6379> MODULE list
1) 1) "name"
   2) "timeseries"
   3) "ver"
   4) (integer) 9900
```

```
Traceback (most recent call last):
  File "d:/Documents/Docker Projects/Long Short/data_provider/data_provider.py", line 74, in <module>
    r.add(key, ts, rate.close)
  File "D:\Anaconda3\lib\site-packages\redistimeseries\client.py", line 140, in add
    return self.execute_command(self.ADD_CMD, *params)
  File "D:\Anaconda3\lib\site-packages\redis\client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "D:\Anaconda3\lib\site-packages\redis\client.py", line 796, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "D:\Anaconda3\lib\site-packages\redis\client.py", line 314, in bool_ok
    return nativestr(response) == 'OK'
  File "D:\Anaconda3\lib\site-packages\redis\_compat.py", line 121, in nativestr
    return x if isinstance(x, str) else x.decode('utf-8', 'replace')
AttributeError: 'int' object has no attribute 'decode'
```
Maybe I have a old version of timeseries module or doing something wrong.

Thanks,

**Comment by ashtul** [comment]
Fixed in PR #13
