### ISSUE TITLE
Response of TS.ADD is incorrectly parsed

### ISSUE THREAD

**Issue by nosqlgeek** [RedisTimeSeries/redistimeseries-py#16]
I am getting the following error message when trying to add an entry to the time series:

```
AttributeError: 'long' object has no attribute 'encode'
```

The command which I am using is:

```
rts.add(timeseries, ts, v)
```

I took a quick look and it seems that it's expected that the return value is a string (i.e. OK) but it is a number (i.e. the timestamp itself). Here the full stack trace:

```
Traceback (most recent call last):
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/1-load.py", line 52, in <module>
    load_to_db(con, "prices.json", prices_ts)
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/1-load.py", line 40, in load_to_db
    con.add(timeseries, ts, v)
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/venv/lib/python2.7/site-packages/redistimeseries/client.py", line 140, in add
    return self.execute_command(self.ADD_CMD, *params)
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/venv/lib/python2.7/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/venv/lib/python2.7/site-packages/redis/client.py", line 795, in parse_response
    return self.response_callbacks[command_name](response, **options)
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/venv/lib/python2.7/site-packages/redis/client.py", line 314, in bool_ok
    return nativestr(response) == 'OK'
  File "/Users/david/Drive/Local/Users/david/Projects/Git/redislabs-training/enablement-timeseries/src/bitcoin-courses/venv/lib/python2.7/site-packages/redis/_compat.py", line 90, in nativestr
    return x if isinstance(x, str) else x.encode('utf-8', 'replace')
```

**Comment by K-Jo** [comment]
introduced by https://github.com/RedisTimeSeries/RedisTimeSeries/issues/120

**Comment by ashtul** [comment]
@K-Jo @gkorland 
It was corrected in PR #13 but wasn't updated on PyPi.

**Comment by ashtul** [comment]
@gkorland @nosqlgeek 
There is an open PR for change of signature for incrby/decrby for the TS and TS-py. If we can incorporate it today we won't have to update PyPi twice.

**Comment by gkorland** [comment]
We didn't agree in incrby new api

**Comment by ashtul** [comment]
@nosqlgeek PyPi package was just updated.
Please retry to confirm problem was solved.
