### ISSUE TITLE
pip3 install fails for 0.6.0

### ISSUE THREAD

**Issue by michaelplaing** [RedisTimeSeries/redistimeseries-py#34]
```
tmp$ python3 -m venv venv
tmp$ python3 -V
Python 3.7.5
tmp$ . venv/bin/activate
(venv) tmp$ pip3 install redistimeseries
Collecting redistimeseries
  Using cached https://files.pythonhosted.org/packages/d4/85/8c3eed73bfcb6dac76ad3d969ff697b6e2487ed1afd8b9ad0f89439a6230/redistimeseries-0.6.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/lv/1p45n8h56_s5w8mrqf2dqt8hgc6rhp/T/pip-install-03z2ahv1/redistimeseries/setup.py'"'"'; __file__='"'"'/private/var/folders/lv/1p45n8h56_s5w8mrqf2dqt8hgc6rhp/T/pip-install-03z2ahv1/redistimeseries/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/lv/1p45n8h56_s5w8mrqf2dqt8hgc6rhp/T/pip-install-03z2ahv1/redistimeseries/pip-egg-info
         cwd: /private/var/folders/lv/1p45n8h56_s5w8mrqf2dqt8hgc6rhp/T/pip-install-03z2ahv1/redistimeseries/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lv/1p45n8h56_s5w8mrqf2dqt8hgc6rhp/T/pip-install-03z2ahv1/redistimeseries/setup.py", line 8, in <module>
        requirements = map(str.strip, open("requirements.txt").readlines())
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by gkorland** [comment]
@michaelplaing thanks for the feedback.
A new release 0.6.1 was published with the fix.
